#!/bin/sh
set -e
set -x
k0sctl apply
k0sctl kubeconfig > ~/.kube/config

# make sure there are nodes ...
echo "await node to be ready:"
sleep 10
kubectl wait --for=condition=Ready nodes --all --timeout=600s

./setup-ingress
./setup-cert-manager michael@schmizzolin.de
helm install hello oci://ghcr.io/mlhartme/charts/hello --version 2.0.0
