#!/bin/sh
set -e

if [ "$#" -ne 0 ] ; then
  echo "setup-ingress does not take any arguments"
  exit 1
fi

echo "installing nginx ingress controller on NodePort ..."
echo "  see https://github.com/kubernetes/ingress-nginx"
echo "  see https://docs.k0sproject.io/v1.22.1+k0s.1/examples/nginx-ingress/"
echo
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/baremetal/deploy.yaml

echo
# nginx is the only ingress controller, mark this in the configuration:
kubectl -n ingress-nginx annotate ingressclasses nginx ingressclass.kubernetes.io/is-default-class="true" 

echo
export HTTP_PORT=$(kubectl get service/ingress-nginx-controller -n ingress-nginx -o jsonpath='{.spec.ports[?(@.name=="http")].nodePort}')
export HTTPS_PORT=$(kubectl get service/ingress-nginx-controller -n ingress-nginx -o jsonpath='{.spec.ports[?(@.name=="https")].nodePort}')

echo "mapping node ports ${HTTP_PORT}/${HTTPS_PORT} to 80/443 ..."
cat http-connector.yaml | envsubst | kubectl apply -f -

echo
echo "await startup ..."
kubectl wait deployment -n ingress-nginx ingress-nginx-controller --for condition=Available=True --timeout=90s
kubectl wait deployment -n http-connector http-connector --for condition=Available=True --timeout=90s

echo
echo "ingress setup done."
