#!/bin/sh
if [ "$#" -ne 1 ] ; then
  echo "installs cert-manager and a letencrypt issuer into the current kubernetes context"
  echo "usage: cert-manager <email>"
  exit 1
fi
set -e

echo "installing cert manager ..."
echo "as documented here: https://cert-manager.io/docs/installation/kubectl/"
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml

echo
echo "await startup ..."
kubectl wait deployment -n cert-manager cert-manager --for condition=Available=True --timeout=90s
kubectl wait deployment -n cert-manager cert-manager-cainjector cert-manager-webhook --for condition=Available=True --timeout=90s
kubectl wait deployment -n cert-manager cert-manager-webhook --for condition=Available=True --timeout=90s

echo
echo "configuring let's encrypt issuer with email ${email}"
echo "as documented here: https://cert-manager.io/docs/configuration/acme/"

export EMAIL=$1
cat cluster-issuer.yaml | envsubst | kubectl apply -f -

echo
echo "done, check with 'kubectl describe ClusterIssuer'"
