apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: mops.schmizzolin.de
      user: root
      port: 22
      keyPath: /Users/mhm/.ssh/id_rsa
    role: single
  k0s:
    version: 1.25.2+k0s.0
    dynamicConfig: false
