#!/bin/sh
if [ "$#" -ne 1 ] ; then
  echo "installs cert-manager and a letencrypt issuer into the current kubernetes context"
  echo "usage: cert-manager <email>"
  exit 1
fi
set -e
email=$1

echo "installing cert manager ..."
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml

echo
echo "await startup ..."
kubectl wait deployment -n cert-manager cert-manager --for condition=Available=True --timeout=90s
kubectl wait deployment -n cert-manager cert-manager-cainjector cert-manager-webhook --for condition=Available=True --timeout=90s
kubectl wait deployment -n cert-manager cert-manager-webhook --for condition=Available=True --timeout=90s

echo
echo "installing let's encrypt issuer with email ${email}"

file=file.txt
cat >$file <<PART1
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
PART1
echo "    email: $email" >>$file
cat >>$file <<PART2
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letencrypt-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
PART2
kubectl apply -f $file
rm $file

echo
echo "done, check with 'kubectl describe ClusterIssuer'"
