name: "${project.artifactId}"
extends: "kutter"
properties:
  image: "${dockerbuild.image}"
  buildScm:
    extra: true
    value: "${project.scm.url}"
  buildOrigin: 
    extra: true
    value: "${dockerbuild.origin}"
