apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: main
        image: {{ .Values.repositoryTag }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 2
          requests:
            cpu: 200m
        env:
          - name: OPTS
            value: "-Dserver.tomcat.basedir=/usr/local/hello/run -Dserver.tomcat.accesslog.enabled=true -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,quiet=n,address=8000"
